# Generated by Django 4.0.2 on 2022-02-15 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_availabilty_user_friday_user_monday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='user',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='user',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='user',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wednesday',
        ),
    ]
