# Generated by Django 4.0.2 on 2022-02-15 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='availabilty',
        ),
    ]
