# Generated by Django 4.0.2 on 2022-02-15 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indecoders_back', '0002_alter_lfwork_email_alter_lfwork_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lfhelp',
            name='availability_desired',
        ),
        migrations.RemoveField(
            model_name='lfwork',
            name='availability',
        ),
    ]
